### PR TITLE
1.1.2.4 User Selection

### PR DESCRIPTION
**Pull request by Aaron-Fink**
Allows user to click on thumbnail image and change which style is currently selected. Tests passing for this module.

### CODE REVIEW

**Review by greta-schock — APPROVED** [review]
Comments make sense. Question: when working with the results.data array in setCurrentProduct, why did you change setCurrentProduct(results.data[0]) to setCurrentProduct(results.data[1]) on line 20 of client/components/App.jsx? Just for testing?

**Comment by Aaron-Fink** [comment]
Oh yeah, that was my bad. I used it so that I could test to make sure the images appeared in rows of 4. The second item in the array has 6 items whereas the first only has 4. I can change it back if you want.

**Comment by greta-schock** [comment]
No need to change it back! If the test makes sense to you, it is good with me. I was curious more than anything :)

**Comment by Aaron-Fink** [comment]
Good to hear, I'll change it on my working branch so the next commit will have it reset.

**Pull request merged**
